apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJVR0YyWld4YVpXMXNlV0Z1YzJ0NU9tZG9jRjlsUjB0RVoweDRNelk0Y0hCTGNXOW9Va2g1TlhCcmRYbFdZVXRWTWs4eFRWWlJlVWM9IgogICAgICAgIH0KICAgIH0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZWZhdWx0Igp9
type: kubernetes.io/dockerconfigjson
